// apps/admin/src/pages/alerts/ui/AlertsPage.tsx
import {
  Alert,
  Button,
  Chip,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Typography,
} from '@mui/material';
import { useSearchParams } from 'react-router-dom';
import styled from 'styled-components';
import type { AlertStatus } from '@entities/alert';
import type { AlertSeverity } from '@entities/sensor';
import {
  STATUS_FILTERS,
  formatAlertValue,
  formatOpenedAt,
  severityLabel,
  statusLabel,
  useAckAlertMutation,
  useAlertsQuery,
} from '@features/alerts';
import { snackbarStore } from '@features/feedback';
import { useSitesQuery } from '@features/sensors';
import { getApiErrorMessage, isForbiddenError } from '@shared/lib/apiError';
import { OutlinedPaper } from '@shared/ui/OutlinedPaper';
import { PageSpinner } from '@shared/ui/PageSpinner';

const Page = styled.div`
  display: flex;
  flex-direction: column;
  gap: 24px;
`;

const Header = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  flex-wrap: wrap;
`;

const TableWrap = styled(OutlinedPaper)`
  padding: 0;
  overflow: auto;
`;

const Filters = styled.div`
  display: grid;
  grid-template-columns: repeat(2, minmax(180px, 1fr));
  gap: 16px;

  @media (max-width: 720px) {
    grid-template-columns: 1fr;
  }
`;

function severityColor(severity: AlertSeverity): 'warning' | 'error' {
  return severity === 'critical' ? 'error' : 'warning';
}

function statusColor(status: AlertStatus): 'default' | 'warning' | 'info' | 'success' {
  switch (status) {
    case 'open':
      return 'warning';
    case 'acked':
      return 'info';
    case 'resolved':
      return 'success';
    default:
      return 'default';
  }
}

export function AlertsPage() {
  const [params, setParams] = useSearchParams();
  const siteId = params.get('siteId') ?? '';
  const status = (params.get('status') ?? '') as AlertStatus | '';

  const sitesQuery = useSitesQuery();
  const alertsQuery = useAlertsQuery({
    siteId: siteId || undefined,
    status: status || undefined,
  });
  const ackMutation = useAckAlertMutation();

  const sites = sitesQuery.data ?? [];

  const setFilter = (key: 'siteId' | 'status', value: string) => {
    const next = new URLSearchParams(params);
    if (value) {
      next.set(key, value);
    } else {
      next.delete(key);
    }
    setParams(next, { replace: true });
  };

  const handleAck = (id: string) => {
    ackMutation.mutate(id, {
      onSuccess: () => {
        snackbarStore.show('Алерт подтверждён', 'success');
      },
      onError: (error) => {
        snackbarStore.show(getApiErrorMessage(error, 'Не удалось подтвердить алерт'), 'error');
      },
    });
  };

  const error = sitesQuery.error ?? alertsQuery.error;

  if (sitesQuery.isPending || alertsQuery.isPending) {
    return <PageSpinner />;
  }

  return (
    <Page>
      <Header>
        <Typography variant="h4">Алерты</Typography>
      </Header>

      {error ? (
        <Alert
          severity={isForbiddenError(error) ? 'warning' : 'error'}
          action={
            <Button
              color="inherit"
              size="small"
              onClick={() => {
                void sitesQuery.refetch();
                void alertsQuery.refetch();
              }}
            >
              Повторить
            </Button>
          }
        >
          {getApiErrorMessage(error, 'Не удалось загрузить алерты')}
        </Alert>
      ) : null}

      <OutlinedPaper>
        <Filters>
          <FormControl>
            <InputLabel id="filter-alert-site">Объект</InputLabel>
            <Select
              labelId="filter-alert-site"
              label="Объект"
              value={siteId}
              onChange={(event) => setFilter('siteId', event.target.value)}
            >
              <MenuItem value="">Все объекты</MenuItem>
              {sites.map((site) => (
                <MenuItem key={site.id} value={site.id}>
                  {site.name} ({site.code})
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          <FormControl>
            <InputLabel id="filter-alert-status">Статус</InputLabel>
            <Select
              labelId="filter-alert-status"
              label="Статус"
              value={status}
              onChange={(event) => setFilter('status', event.target.value)}
            >
              {STATUS_FILTERS.map((option) => (
                <MenuItem key={option.value || 'all'} value={option.value}>
                  {option.label}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
        </Filters>
      </OutlinedPaper>

      {!error && (alertsQuery.data?.length ?? 0) === 0 ? (
        <Alert severity="info">
          Алерты не найдены. Измените фильтр или дождитесь новых событий.
        </Alert>
      ) : null}

      {(alertsQuery.data?.length ?? 0) > 0 ? (
        <TableWrap>
          <TableContainer>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell>Severity</TableCell>
                  <TableCell>Датчик</TableCell>
                  <TableCell>Сообщение</TableCell>
                  <TableCell>Значение</TableCell>
                  <TableCell>Opened</TableCell>
                  <TableCell>Статус</TableCell>
                  <TableCell align="right" />
                </TableRow>
              </TableHead>
              <TableBody>
                {alertsQuery.data?.map((alert) => {
                  const isAcking = ackMutation.isPending && ackMutation.variables === alert.id;

                  return (
                    <TableRow key={alert.id} hover>
                      <TableCell>
                        <Chip
                          size="small"
                          label={severityLabel(alert.severity)}
                          color={severityColor(alert.severity)}
                          variant="outlined"
                        />
                      </TableCell>
                      <TableCell>
                        {alert.sensor.code}
                        <Typography variant="caption" color="text.secondary" component="div">
                          {alert.sensor.name}
                        </Typography>
                      </TableCell>
                      <TableCell>{alert.message}</TableCell>
                      <TableCell>
                        {formatAlertValue(alert.value)} {alert.sensor.unit}
                      </TableCell>
                      <TableCell>{formatOpenedAt(alert.openedAt)}</TableCell>
                      <TableCell>
                        <Chip
                          size="small"
                          label={statusLabel(alert.status)}
                          color={statusColor(alert.status)}
                          variant="outlined"
                        />
                      </TableCell>
                      <TableCell align="right">
                        {alert.status === 'open' ? (
                          <Button
                            size="small"
                            variant="contained"
                            disabled={isAcking}
                            onClick={() => handleAck(alert.id)}
                          >
                            {isAcking ? '…' : 'Ack'}
                          </Button>
                        ) : null}
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </TableContainer>
        </TableWrap>
      ) : null}
    </Page>
  );
}

// apps/viewer/src/pages/AlertsPage.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import type { AlertStatus } from '@/api/alertsApi';
import PageHeader from '@/components/PageHeader.vue';
import { useSelectedSite } from '@/composables/useSelectedSite';
import { useAckAlertMutation } from '@/queries/useAckAlertMutation';
import { useAlertsQuery } from '@/queries/useAlertsQuery';

const statusFilter = ref<AlertStatus | ''>('');

const statusOptions: Array<{ title: string; value: AlertStatus | '' }> = [
  { title: 'Все', value: '' },
  { title: 'Open', value: 'open' },
  { title: 'Acked', value: 'acked' },
  { title: 'Resolved', value: 'resolved' },
];

const { selectedSiteId, selectedSite } = useSelectedSite();
const alertsQuery = useAlertsQuery(selectedSiteId, statusFilter);
const ackMutation = useAckAlertMutation();

const alerts = computed(() => {
  return alertsQuery.data.value ?? [];
});

const subtitle = computed(() => {
  if (!selectedSiteId.value) {
    return 'Выбери site в шапке';
  }

  if (alertsQuery.isPending.value) {
    return 'Загружаем alerts…';
  }

  if (selectedSite.value) {
    return `${selectedSite.value.code} — ${alerts.value.length} записей`;
  }

  return `Site ${selectedSiteId.value}`;
});

function formatTime(value: string | null) {
  if (!value) {
    return '—';
  }

  return new Date(value).toLocaleString();
}

function severityColor(severity: string) {
  if (severity === 'critical') {
    return 'error';
  }

  return 'warning';
}

function statusColor(status: string) {
  if (status === 'open') {
    return 'error';
  }

  if (status === 'acked') {
    return 'warning';
  }

  return 'success';
}

function isAcking(id: string) {
  return ackMutation.isPending.value && ackMutation.variables.value === id;
}
</script>

<template>
  <section>
    <PageHeader title="Алерты" :subtitle="subtitle" />

    <v-select
      v-model="statusFilter"
      :items="statusOptions"
      class="mb-4"
      density="compact"
      hide-details
      item-title="title"
      item-value="value"
      label="Статус"
      max-width="220"
      variant="outlined"
    />

    <v-alert
      v-if="ackMutation.isError.value"
      class="mb-4"
      max-width="36rem"
      type="error"
      variant="tonal"
    >
      Не удалось подтвердить алерт.
    </v-alert>

    <v-alert
      v-if="alertsQuery.isError.value"
      class="mb-4"
      max-width="36rem"
      type="error"
      variant="tonal"
    >
      Не удалось загрузить alerts. Проверь BFF на :3000.
    </v-alert>

    <v-progress-linear
      v-if="alertsQuery.isPending.value"
      class="mb-4"
      color="primary"
      indeterminate
    />

    <v-alert
      v-else-if="selectedSiteId && !alerts.length && !alertsQuery.isError.value"
      max-width="36rem"
      type="info"
      variant="tonal"
    >
      Алертов нет.
    </v-alert>

    <v-card v-else-if="alerts.length" class="alerts-card" variant="outlined">
      <v-table class="alerts-table" density="comfortable">
        <thead>
          <tr>
            <th>Открыт</th>
            <th>Датчик</th>
            <th>Severity</th>
            <th>Статус</th>
            <th class="text-end">Значение</th>
            <th>Сообщение</th>
            <th class="text-end">Действие</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="alert in alerts" :key="alert.id">
            <td class="text-no-wrap">{{ formatTime(alert.openedAt) }}</td>
            <td class="font-weight-medium">{{ alert.sensor?.code ?? alert.sensorId }}</td>
            <td>
              <v-chip :color="severityColor(alert.severity)" size="small" variant="tonal">
                {{ alert.severity }}
              </v-chip>
            </td>
            <td>
              <v-chip :color="statusColor(alert.status)" size="small" variant="tonal">
                {{ alert.status }}
              </v-chip>
            </td>
            <td class="text-end font-weight-medium">{{ alert.value }}</td>
            <td>{{ alert.message }}</td>
            <td class="text-end">
              <v-btn
                v-if="alert.status === 'open'"
                :loading="isAcking(alert.id)"
                color="primary"
                size="small"
                variant="tonal"
                @click="ackMutation.mutate(alert.id)"
              >
                Ack
              </v-btn>
              <span v-else class="text-medium-emphasis">—</span>
            </td>
          </tr>
        </tbody>
      </v-table>
    </v-card>
  </section>
</template>

<style scoped>
.alerts-card {
  overflow: hidden;
  border-color: rgba(var(--v-border-color), var(--v-border-opacity));
}

.alerts-table :deep(thead th) {
  background: rgba(var(--v-theme-primary), 0.12) !important;
  color: rgb(var(--v-theme-primary)) !important;
  opacity: 1 !important;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  border-bottom: 1px solid rgba(var(--v-theme-primary), 0.35) !important;
}

.alerts-table :deep(tbody tr:hover) {
  background: rgba(var(--v-theme-primary), 0.04);
}
</style>
